timeOfDay = profileNamespace getVariable ["DCO_timeOfDay", 0];
publicVariable "timeOfDay";
month = profileNamespace getVariable ["DCO_month", 0];
publicVariable "month";
day = profileNamespace getVariable ["DCO_day", 0];
publicVariable "day";
weatherOvercast = profileNamespace getVariable ["DCO_weatherOvercast", "RANDOM"];
publicVariable "weatherOvercast";
aiSkill = profileNamespace getVariable ["DCO_aiSkill", 0];
publicVariable "aiSkill";
aiMultiplier = profileNamespace getVariable ["DCO_aiMultiplier", 1];
publicVariable "aiMultiplier";
numObjectives = profileNamespace getVariable ["DCO_numObjectives", 0];
publicVariable "numObjectives";
aoOptionSelect = profileNamespace getVariable ["DCO_aoOptionSelect", 0];
publicVariable "aoOptionSelect";
minesEnabled = profileNamespace getVariable ["DCO_minesEnabled", 0];
publicVariable "minesEnabled";
reviveDisabled = profileNamespace getVariable ["DCO_reviveDisabled", 0];
	publicVariable "reviveDisabled";
diag_log "DRO: variables loaded from profile";

//ACE Variables
ACE_repengineerSetting_Repair = profileNamespace getVariable ["DCO_ACE_repengineerSetting_Repair", 0];
publicVariable "ACE_repengineerSetting_Repair";
ACE_repconsumeItem_ToolKit = profileNamespace getVariable ["DCO_ACE_repconsumeItem_ToolKit", 0];
publicVariable "ACE_repconsumeItem_ToolKit";
ACE_repwheelRepairRequiredItems = profileNamespace getVariable ["DCO_ACE_repwheelRepairRequiredItems", 0];
publicVariable "ACE_repwheelRepairRequiredItems";
ACE_medenableRevive = profileNamespace getVariable ["DCO_ACE_medenableRevive", 1];
publicVariable "ACE_medenableRevive";
ACE_medmaxReviveTime = profileNamespace getVariable ["DCO_ACE_medmaxReviveTime", 300];
publicVariable "ACE_medmaxReviveTime";
ACE_medamountOfReviveLives = profileNamespace getVariable ["DCO_ACE_medamountOfReviveLives", 0];
publicVariable "ACE_medamountOfReviveLives";
ACE_medLevel = profileNamespace getVariable ["DCO_ACE_medLevel", 0];
publicVariable "ACE_medLevel";
ACE_medmedicSetting = profileNamespace getVariable ["DCO_ACE_medmedicSetting", 1];
publicVariable "ACE_medmedicSetting";
ACE_medenableScreams = profileNamespace getVariable ["DCO_ACE_medenableScreams", 0];
publicVariable "ACE_medenableScreams";
ACE_medenableUnconsciousnessAI = profileNamespace getVariable ["DCO_ACE_medenableUnconsciousnessAI", 0];
publicVariable "ACE_medenableUnconsciousnessAI";
ACE_medpreventInstaDeath = profileNamespace getVariable ["DCO_ACE_medpreventInstaDeath", 1];
publicVariable "ACE_medpreventInstaDeath";
ACE_medbleedingCoefficient = profileNamespace getVariable ["DCO_ACE_medbleedingCoefficient", 2];
publicVariable "ACE_medbleedingCoefficient";
ACE_medpainCoefficient = profileNamespace getVariable ["DCO_ACE_medpainCoefficient", 10];
publicVariable "ACE_medpainCoefficient";
ACE_medenableAdvancedWounds = profileNamespace getVariable ["DCO_ACE_medenableAdvancedWounds", 0];
publicVariable "ACE_medenableAdvancedWounds";
ACE_medmedicSetting_PAK = profileNamespace getVariable ["DCO_ACE_medmedicSetting_PAK", 0];
publicVariable "ACE_medmedicSetting_PAK";
ACE_medconsumeItem_PAK = profileNamespace getVariable ["DCO_ACE_medconsumeItem_PAK", 0];
publicVariable "ACE_medconsumeItem_PAK";
ACE_medmedicSetting_SurgicalKit = profileNamespace getVariable ["DCO_ACE_medmedicSetting_SurgicalKit", 0];
publicVariable "ACE_medmedicSetting_SurgicalKit";
ACE_medconsumeItem_SurgicalKit = profileNamespace getVariable ["DCO_ACE_medconsumeItem_SurgicalKit", 0];
publicVariable "ACE_medconsumeItem_SurgicalKit";
diag_log "DCO: ACE variables loaded from profile";